### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mohtme** [Nilsen84/lunar-client-qt#101]
![cracklc](https://user-images.githubusercontent.com/82874688/166684292-c803efd7-5e6e-4c93-9ec0-233a3c00bd35.PNG)
how to fix that ?

**Comment by Crazymanverycrazy** [comment]
Theres more than one fix to this issue. #1 make a new lunar client directory. #2 reinstall the actual lunar client then launch the game, do know that the 2nd one might not always fix your issue. 

There should be plenty of tutorials to do this. Hope this helped and have a great day!

**Comment by Idontknowsorryw** [comment]
None of the 2 worked for me, will I no longer be able to use the Lunar Client QT? :(

**Comment by hanbalahmed** [comment]
i got same issue

**Comment by NotTapir** [comment]
ye, same as mine

**Comment by mohtme** [comment]
me too

**Comment by Nilsen84** [comment]
Open an issue with more details.
