### ISSUE TITLE
Lunar Client Qt does launch lunar client but no window shows

### ISSUE THREAD

**Issue by Studio-Hawaii** [Nilsen84/lunar-client-qt#104]
# Device & Version
Device: Mac Os
Lunar Client Qt Version: 1.2.6
# Bug Description
Hello, I am Trying to launch lunar client qt and it does work.
I tried relaunching and reinstalling but it still does not work.
I also made sure nothing on my mac was preventing a window from showing.
The Launch menu does work but when it launches "java", Nothing works.
If you click any launch button, nothing will show up.
There is pretty much nothing you can do to fix this.
Only the developers can fix it.
I hope this gets fixed soon.

**Comment by Nilsen84** [comment]
Try 1.2.9
