### ISSUE TITLE
Suggestions for lcqt launcher itself

### ISSUE THREAD

**Issue by simplictyy** [Nilsen84/lunar-client-qt#105]
have different directories for every version similar to what lcl and solar tweaks has

![image](https://user-images.githubusercontent.com/71561421/167875747-540989e1-844b-4060-b84d-d3fc7e758dbd.png)
![image](https://user-images.githubusercontent.com/71561421/167875897-13818311-84c8-4827-9325-11804c74b730.png)

**Comment by Nilsen84** [comment]
Might consider adding profiles. Technically every setting could have a per version value. Merging this with #130
