### ISSUE TITLE
Isn't working for 1.18.2

### ISSUE THREAD

**Issue by DonkeyMingo** [Nilsen84/lunar-client-qt#106]
Pls help I am on windows and whenever I am clicking on launch it isn't lauching

**Comment by jarvis-1805** [comment]
The application on windows doesn't start for Minecraft version 1.18.2. Upon selecting version 1.18.2, a window pops up with an unknown error.
![image](https://user-images.githubusercontent.com/56910346/169660915-8524cd43-a2a5-4233-b198-3305f7b604e8.png)

**Comment by jarvis-1805** [comment]
> The application on windows doesn't start for Minecraft version 1.18.2. Upon selecting version 1.18.2, a window pops up with an unknown error. ![image](https://user-images.githubusercontent.com/56910346/169660915-8524cd43-a2a5-4233-b198-3305f7b604e8.png)

The issue was resolved after downloading the same version of Minecraft (1.18.2) and then again starting the lunar-client-qt.

**Comment by C41J** [comment]
It opens but I cant find it
