### ISSUE TITLE
MAKE IT SO OTHER PEOPLE CAN SEE!!!

### ISSUE THREAD

**Issue by ohStrqfed** [Nilsen84/lunar-client-qt#109]

**Comment by ohStrqfed** [comment]
make it so other people can see our cosmetics

**Comment by TheCodeFox-tech** [comment]
I think it works if the other people have LunarQT too, but I'm not sure right now

**Comment by Scherso** [comment]
@ohStrqfed Firstly, this would result in a law suite, thanks

**Comment by Scherso** [comment]
> I think it works if the other people have LunarQT too, but I’m not sure right now

@TheCodeFox-tech Cosmetics are completely clientside, no one can see them apart from the user. Adding our own network would require management of servers, and would cost money.
