### ISSUE TITLE
1.18.1 not loading

### ISSUE THREAD

**Issue by JustSmebody** [Nilsen84/lunar-client-qt#111]
1.8 is working but other versions like 1.18 java window only pop up and does not show anything.
![image](https://user-images.githubusercontent.com/99308592/170432292-3ab7356c-f360-4d38-972b-d671464dbbd4.png)

**Comment by Nilsen84** [comment]
1.2.9 should have fixed this I think.

**Comment by JustSmebody** [comment]
the java window only still pops up and still doesnt show anything
