### ISSUE TITLE
make isn't go

### ISSUE THREAD

**Issue by Samuel095383** [Nilsen84/lunar-client-qt#112]
hello when I run the command make me from this error would you give me a hand?

error:
[  4%] Copying 'agents' to 'agents (DON'T TOUCH)'
[  9%] Copying 'libs' to 'libs (DON'T TOUCH)'
[  9%] Built target CopyJars
[ 14%] Automatic MOC and UIC for target lunar-client-qt
[ 14%] Built target lunar-client-qt_autogen
Consolidate compiler generated dependencies of target lunar-client-qt
[ 19%] Building CXX object CMakeFiles/lunar-client-qt.dir/src/launch/offlinelauncher.cpp.o
/home/samuel095383/Scrivania/lunar-client-qt/src/launch/offlinelauncher.cpp: In member function ‘virtual void OfflineLauncher::launch(Launcher::CosmeticsState)’:
/home/samuel095383/Scrivania/lunar-client-qt/src/launch/offlinelauncher.cpp:78:23: error: ‘splitCommand’ is not a member of ‘QProcess’
   78 |     args << QProcess::splitCommand(config.jvmArgs);
      |                       ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/lunar-client-qt.dir/build.make:128: CMakeFiles/lunar-client-qt.dir/src/launch/offlinelauncher.cpp.o] Errore 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/lunar-client-qt.dir/all] Errore 2
make: *** [Makefile:91: all] Errore 2

**Comment by Nilsen84** [comment]
Your version of Qt is outdated. Don't use any distribution based on Ubuntu 20.04.
