### ISSUE TITLE
Cosmetics button not working.

### ISSUE THREAD

**Issue by Yuttoh** [Nilsen84/lunar-client-qt#113]
Hello goodnight! How are you? When I enter my Minecraft through LCQT, when it opens, I go to the cosmetics tab but when I click it it doesn't work, I exit and enter the game, I enter servers and even other menus, but it still doesn't work (The emotes tab still working without problems) If you can fix the problem or tell me the solution I will be grateful.

**Comment by mortadhagh** [comment]
If you use a crack account the cosmetics do not work i think.

**Comment by Yuttoh** [comment]
> Se você usa uma conta de crack, os cosméticos não funcionam, eu acho.

I am not using "Cracked Account" My Minecraft is Original.

**Comment by mortadhagh** [comment]
> 
If I understood correctly cosmetics are provided via a websocket, on Solar Tweaks when the webscoket does not load it advises to reset the config file, also check that you have activated the option to display cosmetics on Lunar.
Good luck !

**Comment by Nilsen84** [comment]
Bruv what do you mean it doesn't work. Open an issue with more details.
