### ISSUE TITLE
Issue about Shields and Moving Items and placing blocks

### ISSUE THREAD

**Issue by Kuurayami** [Nilsen84/lunar-client-qt#114]
- In lunar client qt, version 1.18.2 the shield, moving items & placing blocks have issues.
- The first issue is moving items your items around. Can you please fix where we have to drag items instead to our hot bar or any sort of place and fix the part where we cant instantly make 64 oak logs into wooden planks or for any sort of crafting where you cant shift to make them all instantly into the things we wanted them to be.
- The 2nd issue is where sometimes the shield doesnt work. When you right click at times the shield malfunctions and you arent able to block.
- The last issue is that sometimes when you try to place blocks you arent able to place blocks/water/lava.

**Comment by DirectivesMods** [comment]
These arent lcqt issues
