### ISSUE TITLE
Lunar Client QT not launch in Linux

### ISSUE THREAD

**Issue by dragondemon111311** [Nilsen84/lunar-client-qt#116]
i cant launch Lunar client QT in Linux
the distro im using is: Pop_OS the lastest version

**Comment by Monmcgt** [comment]
You tried to open lcqt but nothing happened?

**Comment by VegardMatthey** [comment]
> i cant launch Lunar client QT in Linux the distro im using is: Pop_OS the lastest version

If you launch the program from the terminal it might give some useful output. I have a similar problem and get this output:
./lunar-client-qt: error while loading shared libraries: libQt5Svg.so.5: cannot open shared object file: No such file or directory
I also tried building it but that did not work either.

**Comment by VegardMatthey** [comment]
I found a fix. I believe that you have not installed the qt5-svg package. I installed it and it works now.

**Comment by dragondemon111311** [comment]
> I found a fix. I believe that you have not installed the qt5-svg package. I installed it and it works now.

Thanks you
It work now. 
I dont know how to run from terminal so i have to build it myself 
But with your help i know im missing qt5 and svg package
