### ISSUE TITLE
Lunar Client QT Not Safe?

### ISSUE THREAD

**Issue by yourprojec** [Nilsen84/lunar-client-qt#117]
when i run lunar-client-qt.exe my windows defender is blocking it

**Comment by Monmcgt** [comment]
It's safe
You can look through the code and build it yourself
btw I recommend download a better antivirus program (I used to use Kaspersky)

**Comment by Mitsobabis** [comment]
> It's safe You can look through the code and build it yourself btw I recommend download a better antivirus program (I used to use Kaspersky)

Same, I use kaspersky too. It's nice

**Comment by Nilsen84** [comment]
Yeah it's a virus, my bad.

**Comment by DirectivesMods** [comment]
windows defender flags any .exe file you run👍

**Comment by Mitsobabis** [comment]
> Yeah it's a virus, my bad.

🤣🤣🤣🤣
