### ISSUE TITLE
i cant open the file in linux terminal

### ISSUE THREAD

**Issue by xoUwUox** [Nilsen84/lunar-client-qt#118]
i get this error

smp@penguin:~/Lunar Client Qt$ ./lunar-client-qt
./lunar-client-qt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./lunar-client-qt)

**Comment by VegardMatthey** [comment]
which distro?

**Comment by Nilsen84** [comment]
The executable is compiled on arch, if you're using a distro with outdated libraries you have to compile it yourself.
