### ISSUE TITLE
1.8 lunar client qt bugs 

### ISSUE THREAD

**Issue by simplictyy** [Nilsen84/lunar-client-qt#12]
cosmetics not appearing
![image](https://user-images.githubusercontent.com/71561421/149258455-0f561104-9636-43a5-b2d8-8fcddc14ac0d.png)

all of avatar emotes are gone (rest of emotes are fine)
![image](https://user-images.githubusercontent.com/71561421/149258745-001d5e0a-7a2e-4c21-a796-eee8a0ab8be8.png)
![image](https://user-images.githubusercontent.com/71561421/149258794-fe9280b5-35fa-422d-80dc-6e18e91bcb6c.png)

xray opacity not working
![image](https://user-images.githubusercontent.com/71561421/149258632-e202c626-f706-4895-82c2-a110dc277efd.png)
![image](https://user-images.githubusercontent.com/71561421/149258680-d7d8a485-47d1-4282-95b9-8e31d0becd99.png)

**Comment by Nilsen84** [comment]
Does it still not work?
