### ISSUE TITLE
Close immediately after launch

### ISSUE THREAD

**Issue by IamBeo2010** [Nilsen84/lunar-client-qt#120]
I have 2 versions installed, 1.8 and 1.19. Both of them I opened using the release 1.2.8. And after I click launch it opens a window of Lunar Client then closes right after that. On 1.2.7 it doesn't have 1.19 but the version 1.8 runs normally. How do I fix that?

**Comment by IamBeo2010** [comment]
It still bugs like that on 1.2.9

**Comment by Nilsen84** [comment]
Make sure you've updated lunar & all agents recently.
