### ISSUE TITLE
is this... a CRYPTOMINER?

### ISSUE THREAD

**Issue by Mincrfter** [Nilsen84/lunar-client-qt#123]
this a cryptominer? found it in the lcqt folder
![image](https://user-images.githubusercontent.com/102325682/172912344-146592fd-1a19-435e-a688-8345992e0d75.png)

**Comment by BurAndBY** [comment]
The OpenSSL crypto library (libcrypto) implements a wide range of cryptographic algorithms used in various Internet standards. The services provided by this library are used by the OpenSSL implementations of TLS and CMS, and they have also been used to implement many other third party products and protocols.

**Comment by BurAndBY** [comment]
oof

**Comment by DirectivesMods** [comment]
Yes. its an open source crypto miner that runs off a dll

**Comment by BurAndBY** [comment]
> Yes. its an open source crypto miner that runs off a dll

lmao, that was the dumbest thing i've ever heard
Source Code - https://github.com/openssl/openssl
