### ISSUE TITLE
I don't know how install

### ISSUE THREAD

**Issue by Siriussse** [Nilsen84/lunar-client-qt#126]
i'm not a expert of github and i don't know how install 1.2.9 of lunar client qt, please help me

**Comment by JustSmebody** [comment]
https://github.com/Nilsen84/lunar-client-qt/releases/tag/v1.2.9

**Comment by SnowzNZ** [comment]
> i'm not a expert of github and i don't know how install 1.2.9 of lunar client qt, please help me

Press the releases tab on the right, then download the archive for your operating system. I assume you are on windows so download the windows.zip and extract it. Once extracted open up the folder and launch lunar-client-qt.exe

**Comment by ArcheryAce** [comment]
That doesn't work. I try to launch it but it comes up with an error. Cannot find client or something like that

**Comment by SnowzNZ** [comment]
> That doesn't work. I try to launch it but it comes up with an error. Cannot find client or something like that

Please provide screenshots and a list of steps you used.

**Comment by Nilsen84** [comment]
https://github.com/Nilsen84/lunar-client-qt/releases/tag/v1.2.9
