### ISSUE TITLE
Blocks

### ISSUE THREAD

**Issue by Wemwe2** [Nilsen84/lunar-client-qt#127]
In 1.19 blocks keep glitching

**Comment by SnowzNZ** [comment]
Hi! As 1.19 is a new version there may be some issues. That being said please contact Lunar Client support at https://support.lunarclient.com/support/home as Lunar Client Qt is merely a launcher for Lunar Client.

**Comment by Nilsen84** [comment]
> Hi! As 1.19 is a new version there may be some issues. That being said please contact Lunar Client support at https://support.lunarclient.com/support/home as Lunar Client Qt is merely a launcher for Lunar Client.

This.
