### ISSUE TITLE
can't find version

### ISSUE THREAD

**Issue by Kawub** [Nilsen84/lunar-client-qt#128]
i installed the original lunar client, then installed the lunar client qt folder and cracked account, when i tried to select a version there's no version and tried to launch and says "No version selected! Do you have lunar installed?" how i solve it?

**Comment by HKS-HNS** [comment]
Did you start MC with lunar once?

**Comment by Kawub** [comment]
> Did you start MC with lunar once?

oh i didnt did it, thank you

**Comment by SnowzNZ** [comment]
> > Did you start MC with lunar once?
> 
> oh i didnt did it, thank you

please mark this issue as closed

**Comment by akashishero** [comment]
i have tried twice but it didnt worked
