### ISSUE TITLE
Hello! I really like to use LunarQT cause it have free cosmetics lol, anyways when i go in the saturation mod i shown up everything but the appleskin mod just dont work. I hope you can fix it asap. Ty for making this awesome client

### ISSUE THREAD

**Issue by funnyme69** [Nilsen84/lunar-client-qt#131]
![image](https://user-images.githubusercontent.com/107013601/173977444-e2a76f55-bc7c-43c8-974b-c7295ac25f9c.png)

**Comment by SnowzNZ** [comment]
This is a lunar client related issue not Lunar Client Qt. Please get support from lunar client at https://support.lunarclient.com/support/home

**Comment by Nilsen84** [comment]
> This is a lunar client related issue not Lunar Client Qt. Please get support from lunar client at https://support.lunarclient.com/support/home

this
