### ISSUE TITLE
Some problem about Qt5Svg Cmakefile.txt thingy

### ISSUE THREAD

**Issue by Purnkmc78** [Nilsen84/lunar-client-qt#133]
Hello there, I was trying to install Lunar Client QT on Linux when this error showed 
![Screenshot from 2022-06-19 14-29-30](https://user-images.githubusercontent.com/105113599/174470595-2e8dab15-2520-41d5-a264-725af078999f.png)

And oh boy, it was **irritating**. I tried and tried to figure out how to fix this but I just have no idea how.
Do you have any idea how to install this without installing Windows for ease?

**Comment by mortadhagh** [comment]
Hello, i had the same error.

**I used this command to fix the problem** : `apt-get install git build-essential cmake qt5-default qtscript5-dev libssl-dev qttools5-dev qttools5-dev-tools qtmultimedia5-dev libqt5svg5-dev libqt5webkit5-dev libsdl2-dev libasound2 libxmu-dev libxi-dev freeglut3-dev libasound2-dev libjack-jackd2-dev libxrandr-dev libqt5xmlpatterns5-dev libqt5xmlpatterns5 libqt5xmlpatterns5-private-dev
`

Maybe It will work for you, Good Luck !

**Comment by Nilsen84** [comment]
`# apt install libqt5svg5-dev `
