### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by MCAki06** [Nilsen84/lunar-client-qt#14]
So I recently passed by this project and this looks interesting, is deleting 'windir' environment variable is really safe?
![image](https://user-images.githubusercontent.com/58387441/149619096-b9a97f28-be0a-487d-ba53-2cd5159e03be.png)

**Comment by ceilingfans** [comment]
yeah it should be fine

**Comment by Youded-byte** [comment]
The "windir" environment variable is removed from the newly created QProcessEnvironment env, which is passed to java instance i.e. lunar client. This environment variable is NOT removed system-wide or from any other process's environment. Therefore it is completely safe.

**Comment by MCAki06** [comment]
Alright thanks, I realized it later on!
