### ISSUE TITLE
no version in showing

### ISSUE THREAD

**Issue by arm4xlll** [Nilsen84/lunar-client-qt#169]
![image](https://user-images.githubusercontent.com/109166895/178545747-d7ddd42a-d791-4c62-a57b-e562c63a3fc0.png)

**Comment by 22Toe** [comment]
Let me tell you in short what happened.
There was a minor update 1-2 days ago which changed the versions path in lunar client due to which lunar qt is not able to Minecraft version.

**Comment by arm4xlll** [comment]
> Let me tell you in short what happened. There was a minor update 1-2 days ago which changed the versions path in lunar client due to which lunar qt is not able to detect Minecraft version.
