### ISSUE TITLE
I cant see the versions

### ISSUE THREAD

**Issue by CodeceRROR** [Nilsen84/lunar-client-qt#186]
![image](https://user-images.githubusercontent.com/109628099/179845101-ffe120e3-a282-4836-976b-6fd5d8f5d0d6.png)

**Comment by buiawpkgew1** [comment]
duplicate question：

1. https://github.com/Nilsen84/lunar-client-qt/issues/182
2. https://github.com/Nilsen84/lunar-client-qt/issues/179
3. https://github.com/Nilsen84/lunar-client-qt/issues/168

**Comment by buiawpkgew1** [comment]
download this try https://github.com/Nilsen84/lunar-client-qt/actions/runs/2691145802

**Comment by CodeceRROR** [comment]
> download this try https://github.com/Nilsen84/lunar-client-qt/actions/runs/2691145802

![image](https://user-images.githubusercontent.com/109628099/179983132-08718364-443c-400c-bed9-ab64df950611.png)

**Comment by Divi4602s** [comment]
client not adding from this method

**Comment by buiawpkgew1** [comment]
> > download this try [Nilsen84/lunar-client-qt/actions/runs/2691145802](https://github.com/Nilsen84/lunar-client-qt/actions/runs/2691145802)
> 
> ![image](https://user-images.githubusercontent.com/109628099/179983132-08718364-443c-400c-bed9-ab64df950611.png)

Sign in with Microsoft

**Comment by CodeceRROR** [comment]
the new version fixed the problem
