### ISSUE TITLE
i am not able to play!!!!!

### ISSUE THREAD

**Issue by 28293943908** [Nilsen84/lunar-client-qt#19]
i have a mac and i downloaded the software and after i click the launch with all cosmetics nothing happens just this will come plz slove it 
<img width="1280" alt="Screenshot 2022-01-25 at 4 21 43 PM" src="https://user-images.githubusercontent.com/76963208/150963436-c4fa15ad-329c-442b-a757-e7d05d2bd2a1.png">

**Comment by Nilsen84** [comment]
Dm me on discord

**Comment by 28293943908** [comment]
Hello Nilsen84 i sent you a friend request this is my disord id= I_COME_FROM_HELL#6925
