### ISSUE TITLE
Solve lunar problems

### ISSUE THREAD

**Issue by craciu25yt** [Nilsen84/lunar-client-qt#20]
Hi. Since 1 week I can't play to some servers using lunar client (that too). I opened ticket and I think they ignored me. Thats for say if u can solve it for that lunar version.

**Comment by Nilsen84** [comment]
? Wdym you can't play to some servers

**Comment by craciu25yt** [comment]
Yes. Like hypixel lunar network... (Some premium and some nopremium)

**Comment by craciu25yt** [comment]
![image](https://user-images.githubusercontent.com/48807342/152002826-03be07ea-62b1-488f-8805-f2125aa6f9e2.png)
![image](https://user-images.githubusercontent.com/48807342/152002853-67033e68-4842-4028-a218-dc26cdbd43f0.png)

**Comment by Nilsen84** [comment]
I won't be able to solve this as I have no idea why it's caused and I can't reproduce this myself.
