### ISSUE TITLE
Entry point Not found

### ISSUE THREAD

**Issue by oussama273** [Nilsen84/lunar-client-qt#23]
when i try to open lunar client qt , it says
![image_2022-01-30_193514](https://user-images.githubusercontent.com/98708416/151712662-9e67748a-9e0e-442b-a4c2-ce02e80c9b97.png)
 "The procedure entry point CreateEventW could not be located in the dynamic link library api-ms-win-core-synch-l1-2-0.dll."

**Comment by Nilsen84** [comment]
Lunar client qt does not work on windows 7. It is recommended to update to 10/11. If you're still on windows 7 for performance reasons I'd recommend switching to linux.
