### ISSUE TITLE
Add Please add Discord group

### ISSUE THREAD

**Issue by buiawpkgew1** [Nilsen84/lunar-client-qt#237]
@Nilsen84

**Comment by xMohammed157** [comment]
Try this link: [](https://discord.gg/n82vQujazw)

**Comment by buiawpkgew1** [comment]
> Try this link: [discord.gg/n82vQujazw](https://discord.gg/n82vQujazw)

Is this your Discord group? 
Not the author's?

**Comment by xMohammed157** [comment]
> > Try this link: [discord.gg/n82vQujazw](https://discord.gg/n82vQujazw)
> 
> Is this your Discord group? Not the author's?

It's the author's discord, they post updates and you can ask for help there.
