### ISSUE TITLE
make it so we can inject some mods

### ISSUE THREAD

**Issue by Wqvx** [Nilsen84/lunar-client-qt#25]
hey i have some ghost clients and some mods like tcpnodelay and hitdelay fix and i wanted to inject them but its wont can u fix it! thanks

**Comment by Altf4lol** [comment]
u cant inject forge mod in lunar

**Comment by Altf4lol** [comment]
i dont think you can inject forge mods on lunar

**Comment by Nilsen84** [comment]
I have my own hitdelay fix mod for lunar which you can download at [https://github.com/Nilsen84/lunar-client-agents](url). Tcpnodelay is implemented into the vanilla client.
