### ISSUE TITLE
cosmetics (cloaks,bandanas,wings) still not working after update

### ISSUE THREAD

**Issue by simplictyy** [Nilsen84/lunar-client-qt#26]
cosmetics (cloaks,bandanas,wings) still not working after update

![image](https://user-images.githubusercontent.com/71561421/152343149-64a155a4-707f-4933-b7ff-ec90ad5448ad.png)

emotes and the java agents work though (NoPinnedServers, StaffEnable, and LunarEnable but i didnt get to record it)
https://streamable.com/2b79uq

**Comment by Nilsen84** [comment]
Update lunar and lcqt.
