### ISSUE TITLE
Cosmetics doesnt work

### ISSUE THREAD

**Issue by devPrzemuS** [Nilsen84/lunar-client-qt#27]
there is just "connecting" when i open a cosmetics menu

**Comment by QTtea** [comment]
yup, emotes and cosmetics broke again

**Comment by wnm210** [comment]
cuz as i think lunar changed they api yesterday

**Comment by Wqvx** [comment]
yeah cosmtics doesnt work and keybind of the emoted not working

**Comment by kingofnetflix** [comment]
![Screenshot 2022-02-04 133529](https://user-images.githubusercontent.com/72701796/152606376-75620d9a-5ef4-4c83-9d32-5348f853d2f0.png)

@Nilsen84 knows the current issues, and is working on a fix. You should close this issue :)

**Comment by Nilsen84** [comment]
Fixed in the latest release.
