### ISSUE TITLE
[Question] Show cosmetics to everybody else

### ISSUE THREAD

**Issue by xFGhoul** [Nilsen84/lunar-client-qt#32]
it seems that the launcher with all cosmetics is only client side, is there any way for it to become server sided?

**Comment by devPrzemuS** [comment]
You can't make it so that everyone sees it. Alternatively, you could do it the same way LCP did it, that is, only people who also use Lunar Client QT would see it.

**Comment by devPrzemuS** [comment]
to be able to make anyone from Lunar see it, you'd have to hack into their servers, or use some vulnerability in the code that guarantees access to the database (i'm pretty sure such a stupid vulnerability doesn't exist)

**Comment by Nilsen84** [comment]
^ In order to do this I'd have to create a custom websocket server. The downside to that is that you wouldn't be able to interact with normal lunar client players (No lunar logo would be shown, no friends menu etc)
