### ISSUE TITLE
Suggestion - Agents

### ISSUE THREAD

**Issue by Dani-error** [Nilsen84/lunar-client-qt#35]
I know this suggestion is weird, but I want to suggest, if you (Nilsen84) can publish the agents src, or make an example of each.
That will be very cool!

**Comment by Dani-error** [comment]
For example, in your profile, you have some agents src, but the cosmetics agent, you don't have...

**Comment by Nilsen84** [comment]
Everything is public except for the cosmetics agent. The cosmetics agent is private because it'd be really easy for lunar to patch it if the source was available.
