### ISSUE TITLE
lunar not launching when start

### ISSUE THREAD

**Issue by iqwe323** [Nilsen84/lunar-client-qt#36]
Hi, when i press launch (tried all launch buttons) it doesn't do anything

**Comment by iqwe323** [comment]
Same with all versions except while launching 1.7 it syas: "failed to start process: unknown error"
![obraz_2022-02-15_134815](https://user-images.githubusercontent.com/99679476/154065131-26dbf40d-ad90-4dd4-b3df-7a8e759f8e6d.png)

**Comment by iqwe323** [comment]
tried older version of lunar client qt and same problem

**Comment by Dn030** [comment]
Try this: https://github.com/Nilsen84/lunar-client-qt/issues/77
