### ISSUE TITLE
Connecting Issue

### ISSUE THREAD

**Issue by Xiliank** [Nilsen84/lunar-client-qt#42]
Hello i know its been **_fixed_** but even if i log out and log in to my minecraft account it shows **_connecting_** and i dont know why this happens cuz i downloaded the newest version i even have the old one and i tried **_both_** but both of them show **_connecting_**
please help me fix this -_-

**Comment by LaBumHole1** [comment]
yh same

**Comment by Nilsen84** [comment]
You have to update lunar by launching the game through the official lc launcher.

**Comment by Nilsen84** [comment]
And you're sure you're on the latest version of lcqt (1.2.3)?

**Comment by Xiliank** [comment]
I think i did but ill check

**Comment by Xiliank** [comment]
yes sir

**Comment by Nilsen84** [comment]
Should be fixed
