### ISSUE TITLE
Custom JREs

### ISSUE THREAD

**Issue by Sarreos** [Nilsen84/lunar-client-qt#44]
Custom JREs are not working on Linux.

**Comment by Nilsen84** [comment]
Not an lcqt issue, custom JREs do work, it's just that they crash right after being opened. This is the output I'm getting, if you're curious:

OpenJDK 17:
![image](https://user-images.githubusercontent.com/56961087/155377752-40a78688-9b57-428e-91dd-3a8e578dd6c5.png)
GraalVM Enterprise:
![image](https://user-images.githubusercontent.com/56961087/155378109-1b48116b-cd0d-448e-b6f6-4c8375c39f65.png)

**Comment by Sarreos** [comment]
Any idea why they are crashing. I recall having this issue with other mc launchers.

**Comment by Sarreos** [comment]
Okay I managed to fix the issue with custom JREs.

**Comment by Sarreos** [comment]
The issue with these JREs is that the libwjgl64.so is missing for some reason. I found a fixed version of this library and just added it to the JRE's library folder.
