### ISSUE TITLE
Make it so that vape v4 and vape lite can inject + cracked logins

### ISSUE THREAD

**Issue by iamleafy1234** [Nilsen84/lunar-client-qt#5]
Make it so that vape v4 and vape lite can inject + cracked logins

**Comment by iamleafy1234** [comment]
rn it crashes vape

**Comment by Nilsen84** [comment]
I have no idea why vape crashes, but it probably has something to do with launching an outdated version of lunar. I might fix this in the future by adding optional auto-updating.

As for the cracked logins, could you clarify what a cracked login is?

**Comment by dremonq** [comment]
> I have no idea why vape crashes, but it probably has something to do with launching an outdated version of lunar. I might fix this in the future by adding optional auto-updating.
> 
> As for the cracked logins, could you clarify what a cracked login is?

Cracked logins are cracked accounts

**Comment by iamleafy1234** [comment]
> 

you can log on with cracked accounts, instead of writing a email and password, just writing a username, the vape crashing thing is over, now it just freezes at 90% loading

**Comment by Nilsen84** [comment]
Just to clarify, you want the ability to specify a username in the launcher that you can use in singleplayer and on cracked servers?

**Comment by dremonq** [comment]
> Just to clarify, you want the ability to specify a username in the launcher that you can use in singleplayer and on cracked servers?

Preety sure he meant that

**Comment by iamleafy1234** [comment]
> Just to clarify, you want the ability to specify a username in the launcher that you can use in singleplayer and on cracked servers?

yea, just writing a ign in the login will make it for cracked and u can play on servers like pika

**Comment by pixlofc** [comment]
> rn it crashes vape

vape works fine, wait for the game to fully load and inject on windowed mode.

**Comment by iTzHard** [comment]
> Just to clarify, you want the ability to specify a username in the launcher that you can use in singleplayer and on cracked servers?

Yes, or alternatively being able to load up single player without being connected to the internet.

**Comment by GamerSick** [comment]
Yea cracked login (also called offline-mode) will help those who are poor/in bad situation who cant buy mc and and want to use the lunar client without an official account :') , just like me.

**Comment by Nilsen84** [comment]
Added cracked logins: https://github.com/Nilsen84/lunar-client-agents

**Comment by minhlongdev** [comment]
make vape crack can inject xd

**Comment by jinja365** [comment]
@Nilsen84 vape got cracked xd https://jelte.one could you make it so that it can inject xd

**Comment by minhlongdev** [comment]
no, it just crash when sent dump1

**Comment by minhlongdev** [comment]
wait i forgot thats u mention nilsen xd

**Comment by jinja365** [comment]
@minhlongdev yeah @Nilsen84 could you fix that not trying to be annoying sorry

**Comment by jinja365** [comment]
@minhlongdev the vape crack support discord server said that they would release lunar mappings tommorow sooo... ig vape crack might be compatible with lunar when they release

**Comment by dremonq** [comment]
> 

Fr??

**Comment by Nilsen84** [comment]
Gonna close this because I don't have any control over vape. Ask the vape devs.

**Comment by jinja365** [comment]
alright
