### ISSUE TITLE
I accidently put a forge mod in lcqt

### ISSUE THREAD

**Issue by DetectiveBjarne** [Nilsen84/lunar-client-qt#55]
I tried every version but same thing after I did all the older versions found out that one of the managers i was using was casually a mod or forge mod can I tried to remove it put it doesn't work

**Comment by Nilsen84** [comment]
?

**Comment by DetectiveBjarne** [comment]
> I have no idea what you are saying, but just remove the Forge mod?

I tried but doesn't work
