### ISSUE TITLE
Bans?

### ISSUE THREAD

**Issue by jinja365** [Nilsen84/lunar-client-qt#58]
will using the 'launch with all cosmetics' get me banned from lunar as its the same thing as LCProxy and that was blacklisted by lunar?

**Comment by Nilsen84** [comment]
No one has gotten banned for using it, afaik lunar doesn't even have a system set up for banning people, however, If lunar were to start issuing bans I will not claim responsibility. Use it at your own risk :)

**Comment by jinja365** [comment]
Well lunar was blacklisting accounts from all their projects like the client, lunar.gg server etc when poeple started using LCProxy in large amounts which severely affected lc in terms of money so yeah i just wanted to confirm

**Comment by jinja365** [comment]
Thanks
