### ISSUE TITLE
Add Fedora/RPM dependency qt5-qtsvg

### ISSUE THREAD

**Issue by Quinten0508** [Nilsen84/lunar-client-qt#59]
On Fedora 35 (and most likely other Fedora and other distro's using RPM) using lunar-client-qt requires the dependency `qt5-qtsvg` to be installed with `sudo dnf install qt5-qtsvg`. Just double clicking the app does not show any error log (and the application does not launch), and running it via a terminal gives a general error message. This makes it difficult for users to diagnose this issue.

Therefore this might be useful to include the above solution somewhere in the installation guide or even better add it as dependency (unsure if this is possible).

**Comment by Nilsen84** [comment]
I can't add a dependency unless I package lunar client qt as an rpm.
