### ISSUE TITLE
1.18 doesn't load?

### ISSUE THREAD

**Issue by ohStrqfed** [Nilsen84/lunar-client-qt#66]
uh whenever i run my minecraft 1.18.1 in lunar-client-qt i can't open it as it just opens a java folder for like 100000 hours.,

**Comment by Nilsen84** [comment]
Wdym "opens a java folder"

**Comment by ohStrqfed** [comment]
not a java folder, i mean a java tab

**Comment by Dn030** [comment]
This might be a problem with your computer, Try running the game with the normal Minecraft Launcher on 1.18. This might also be a JRE Problem but that is near impossible so i highly doubt it

**Comment by Nilsen84** [comment]
Open an issue with more info including settings.
