### ISSUE TITLE
CRASH-271898f7-e433-4aec-b0cb-61ff2d39dcb0

### ISSUE THREAD

**Issue by Yuttoh** [Nilsen84/lunar-client-qt#67]
![Screenshot_10](https://user-images.githubusercontent.com/98183285/162101230-0bab2ce6-85ec-40a9-9e12-d560f8a7b1fe.png)
Hello, Good Night! How is everything? An acquaintance of mine tried to log in with LunarClient QT and gave this error "CRASH-271898f7-e433-4aec-b0cb-61ff2d39dcb0" I don't know if it's a LunarClient error or a LC QT error, if you can see it for me, I'll be grateful, bye!

**Comment by Nilsen84** [comment]
Make sure you're running the latest version of LC QT (1.2.6) and that lunar is updated. Also make sure you do NOT have UnlockCosmetics, NickLevel, CustomLevelHead or CustomAutoGG added to the agents tab.

**Comment by Dn030** [comment]
I think this is a JRE problem. Try this https://github.com/Nilsen84/lunar-client-qt/issues/77

**Comment by Zaltrus** [comment]
didnt work

**Comment by Nilsen84** [comment]
Update lunar & lcqt.
