### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dremonq** [Nilsen84/lunar-client-qt#7]
![Снимак екрана (304)](https://user-images.githubusercontent.com/82154495/148614656-af80fedd-5eaf-4767-902d-f2c8177a481f.png)

**Comment by Nilsen84** [comment]
Make sure you have the version you're trying to launch installed through the official launcher.

**Comment by dremonq** [comment]
> Make sure you have the version you're trying to launch installed through the official launcher.

The Minecraft launcher or lunar launcher

**Comment by Nilsen84** [comment]
Lunar launcher.
