### ISSUE TITLE
Game just won't launch

### ISSUE THREAD

**Issue by Kagulah** [Nilsen84/lunar-client-qt#77]
When I click any button (Launch with cosmetics, Launch without cosmetics and just 'Launch') the launcher closes (Unless I chose for it to stay open) and does nothing, no crash report shows up and it's not in task manager.

**Comment by Dn030** [comment]
Open the application with administrator priveleges, navigate to general. and tick the box named "Use Custome JRE". 

(THE NEXT STEP IS NOT NECESSARY, THIS STEP ONLY APPLIES TO PEOPLE THAT CANT FIND THE FOLDER .lunarclient UNDER 
C:/Users, IF THE FOLDER STILL DOESNT APPEAR SCROLL AT THE BOTTOM OF THE PAGE AND DO THE STEPS THEN YOU MAY CONTIUNING)

press the Windows Logo key and the E key on your keyboard to open file explorer, in linux open terminal (alt + t) and type `sudo nautilus or sudo dolphin` depending of wich file manager you use in linux and then press ctrl + h and exit the process, On Windows I would advise you follow these guides 

Windows 10: https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-97fbc472-c603-9d90-91d0-1166d1d9f4b5#WindowsVersion=Windows_10

Windows 11: https://support.microsoft.com/en-us/windows/view-hidden-files-and-folders-in-windows-97fbc472-c603-9d90-91d0-1166d1d9f4b5 

Now open up Lunar Client Qt and navigate to General->"Use Custom JRE" click the folder icon located to the right of the blank bar. 
Navigate to your C drive, where windows is installed.
Open the Users Folder, If your installation of Windows is in another Langauge this folder called "Users" may be named differntly according to the language of the windows Installation.
Now choose the Windows Account you are currently on.
Open the ".lunarclient" folder
Open Jre
Click on the verison of Minecraft you want to play in my case that is 1.8
There should be a folder named "zulu" and a bunch of characters and numbers after that
Open bin
Scroll down until you find Javaw.exe.
Choose Javaw.exe.

(Linux users are smart enough to know what to do here.)

If you dont have the .lunarclient folder, download lunar client from the original website install it and run the version of minecraft you want and wait till everything downloads and runs, you can now close out of minecraft and uninstall lunar client if you want to.
You will now be able to launch the game without any problems.

**Comment by Nilsen84** [comment]
Open an issue with more info including your settings.
