### ISSUE TITLE
Agent Suggestion (Queue Dodge)

### ISSUE THREAD

**Issue by xvrt** [Nilsen84/lunar-client-qt#79]
Is there a way you/anyone could make a **Hypixel Bedwars Queue Dodge** agent with a command or something easy like that for an easier way to get a higher FKDR?

**Comment by xvrt** [comment]
Like an agent that has a cmd /queue dodge or something and it goes into a game with the people that have the lowest Bedwars star.

**Comment by Nilsen84** [comment]
Use an external overlay/proxy.
