### ISSUE TITLE
suggestion (please read)

### ISSUE THREAD

**Issue by MaybeZac** [Nilsen84/lunar-client-qt#8]
can you make this available on mac, I really love the idea but you have linux and no mac. I probably sound like every other annoying mac user but just think about it

**Comment by MaybeZac** [comment]
thank you

**Comment by Nilsen84** [comment]
It is usable on macos if you build it yourself. The reason I don't have binaries for mac is because I don't own a mac myself, and I'm not familiar with any CI services.

Add me on discord: nils#5281if you want help building.
