### ISSUE TITLE
newer versions: 1.18 won't work

### ISSUE THREAD

**Issue by ocowala** [Nilsen84/lunar-client-qt#88]
when i try opening 1.18.1 or 1.18.2 it doesn't work. The java window pops up but the game doesn't load ever. I am on M1 Macbook Pro

**Comment by ohStrqfed** [comment]
exact same thing happened to me i also have MacBook pro m1 so idk

**Comment by Scherso** [comment]
@ocowala Unfortunately, there’s only 1.8.9 support as of right now with most Java agents.

**Comment by Nilsen84** [comment]
Open a new issue if it still doesn't work
