### ISSUE TITLE
I won't start

### ISSUE THREAD

**Issue by DaBearXx** [Nilsen84/lunar-client-qt#91]
It always give me the same message of "Failed to start process:No program defined" how do I fix this?

**Comment by Oxstann** [comment]
I have the exact same problem

**Comment by BaldLessNoob** [comment]
do you have lunar client installed? 1st install it then launch wait till game opens fully you wont have to login just launch the game ! then check the version is the same as the launcher if this doesnt work see this https://www.youtube.com/watch?v=MBcrtakLFcg&t=67s

**Comment by Nilsen84** [comment]
Fixed in 1.2.9
