### ISSUE TITLE
I CANT START MY GAME

### ISSUE THREAD

**Issue by BaldLessNoob** [Nilsen84/lunar-client-qt#92]
**Hi,Im trying to launch the game the version and everything i should to do so the game should launch but mine is not i dont know what to do Pls this is the best lunar launcher ever i have seen and am a cracked player pls respond fast i even send friend request to you discord waiting till 2 days  for the fiend request  to be accepted but it still hasn't so thats why am submiting a issue**

**Comment by TheCodeFox-tech** [comment]
Could you please provide more information like operating system and LunarQT version? Otherwise it's really hard to resolve your issue.

**Comment by Nilsen84** [comment]
> Could you please provide more information like operating system and LunarQT version? Otherwise it's really hard to resolve your issue.

This.
