### ISSUE TITLE
1.8 cosmetics

### ISSUE THREAD

**Issue by rolcsi05** [Nilsen84/lunar-client-qt#93]
![image](https://user-images.githubusercontent.com/77266343/164910734-f8442cef-6ed7-43b4-b458-b08493ebadfc.png)
Everything works fine other than "launch with all cosmetics" on 1.8 It worked fine before idk

**Comment by LegendDestroyer6584** [comment]
works fine for me

**Comment by EternalDusk** [comment]
You need to start up normal lunar client in that version for it to build the game files.
Go to Lunar Client, select version 1.8, let it install, join a server, and then close and try again. It should work then
