### ISSUE TITLE
Lunar Client Qt collects the classpath incorrectly

### ISSUE THREAD

**Issue by 770grappenmaker** [Nilsen84/lunar-client-qt#96]
**Description**  
Lunar client qt uses all files that exist in the offline/version directory, causing issues if people use that directory for anything else, or if there are still old jars from lunar client in there. For example, some users wanted to upgrade their version of Solar Patcher, but when running lcqt it fallbacked to the old version, because the classpath is specified before all agents and custom arguments. That way, when loading Solar Patcher as an agent, it just used the classes in the classpath instead.

**To reproduce**  
Put a jarfile that shouldn't be in the classpath in the offline/version dir, and run the game.

**Expected behaviour**  
Normal launch, only adding the following files to classpath:
```
lunar-assets-prod-1-optifine.jar
lunar-assets-prod-2-optifine.jar
lunar-assets-prod-3-optifine.jar
lunar-prod-optifine.jar
lunar-libs.jar
vpatcher-prod.jar
```

**Actual behaviour**  
Launches with all files available in the current workdir.

**Diagnosis**  
The error exists on line 44 of [this file](https://github.com/Nilsen84/lunar-client-qt/blob/master/src/launch/offlinelauncher.cpp)

**Comment by Aetopia** [comment]
I assume its wildcarding for `\*.jar`?

**Comment by 770grappenmaker** [comment]
No: it lists all files, while it should only load specific files, or at least just jars. It is also loading vm crash logs :rofl:

**Comment by Nilsen84** [comment]
I'm not aware of any downside to collecting all files. Non relevant files will be ignored and newer jars will be prioritized if multiple jars contain the same classes.

I did it this way because 1.7 requires some optifine file that doesn't have a .jar extension. Collecting all files and sorting them by modification date also comes with the upside of improved compatibility between lunar versions as the launcher would keep working if lunar decides to change the name of the class path files.

**Comment by 770grappenmaker** [comment]
I know about 1.7, it is really weird.
Your point makes sense, but I think I had an edge case with Solar Tweaks because for testing I used to put the patcher in the offline/1.8 directory which breaks it.
Closing because indeed there is no point of fixing this.

**Comment by Aetopia** [comment]
> I'm not aware of any downside to collecting all files. Non relevant files will be ignored and newer jars will be prioritized if multiple jars contain the same classes.
> 
> I did it this way because 1.7 requires some optifine file that doesn't have a .jar extension. Collecting all files and sorting them by modification date also comes with the upside of improved compatibility between lunar versions as the launcher would keep working if lunar decides to change the name of the class path files.

```py
path.split(glob(f'{USERPROFILE}/.lunarclient/offline/{Version}/*OptiFine_*')[0])[1]
```
Why not wildcard for the `Optifine.jar` File?

```py
for Jar in ('lunar-assets-prod-1-optifine.jar',
			'lunar-assets-prod-2-optifine.jar',
			'lunar-assets-prod-3-optifine.jar',
			'lunar-libs.jar',
			'lunar-prod-optifine.jar',
			path.split(glob(f'{USERPROFILE}/.lunarclient/offline/{Version}/*OptiFine_*')[0])[1], 
			'vpatcher-prod.jar'
			):
```

**Comment by 770grappenmaker** [comment]
That's what I'd do, but there is nothing against the current approach.

**Comment by Nilsen84** [comment]
> Why not wildcard for the `Optifine.jar` File?

Because there's no problem with the current approach which has the additional benefit of being guaranteed to work no matter what lunar decides to do with the class path in future versions.
