### ISSUE TITLE
Cloaks not working

### ISSUE THREAD

**Issue by Lucwhan** [Nilsen84/lunar-client-qt#99]
When i first started using lunar client qt the cloaks worked just fine but the day after the cloaks just stopped working every other cosmetic work and idk what to do i play 1.8 btw 
Pls help

**Comment by Lucwhan** [comment]
nvm fixed it

**Comment by Lucwhan** [comment]
comment if u need a fix for this if anyone has the problem

**Comment by NightSling** [comment]
I couldn't fix this issue, how did you fix it? @Lucwhan

**Comment by Lucwhan** [comment]
so i downloaded the agents launched the game 3 times and removed every single one of the agents after except for the cosmetic unlock and it started working again
